### ISSUE TITLE
No feedback

### ISSUE THREAD

**Issue by maxim123** [vianuevm/cppStyle#123]
…when submitting this file: https://gist.githubusercontent.com/justecorruptio/9967738/raw/83f5800e8110046851a4cb654519115607952615/2048.c

**Comment by vianuevm** [comment]
It means an error occurred - we should probably implement logging in the style grader this semester.

**Comment by maxim123** [comment]
An easy fix would be just catching all exceptions in the main function and printing "an error occurred". This is better than giving no feedback at all.

**Comment by TheWolfA2** [comment]
Probably fixed in 3c68ae0cffc69904c9fb4be6be6bab41328e0c34?  Added checks for &= and |= in 90bb03ad056d33a17eb6451daea2c84060cb1fb6 although students shouldn't ever need to use these
