### ISSUE TITLE
Layout on smaller screens

### ISSUE THREAD

**Issue by maxim123** [vianuevm/cppStyle#125]
This can be fixed by using bootstrap's grid.

![screen shot 2015-01-10 at 8 34 35 pm](https://cloud.githubusercontent.com/assets/5017937/5693999/241015de-9908-11e4-85e8-b119fbce58cb.png)

**Comment by willwolf** [comment]
Should have been fixed in f6b626d6daf169dc1b23eba538c6b43454fb09cd :)
