### ISSUE TITLE
flags '/' as error

### ISSUE THREAD

**Issue by gzuroff** [vianuevm/cppStyle#126]
getline(pararm1, param2, '/') flags '/' as an error.

**Comment by dharapa** [comment]
I spotted this too; I think it's because the style grader is looking for spaces on either side of the symbol since it is typically used for division and not taking into account that / can be a char.

**Comment by willwolf** [comment]
This issue should have been fixed in 87bc0e1b38d50c3ae7f242c35ea702d78e82d71d. If you could resubmit the code that caused the issue and verify it works, I would greatly appreciate it! If it's still broken, please reopen the issue and let me know :)
