### ISSUE TITLE
Possible Problem With Logical Negation Operator

### ISSUE THREAD

**Issue by dharapa** [vianuevm/cppStyle#127]
Receiving an error: "Incorrect spacing around !.  If this is a negative variable, you must write it as -(myVariable) using parentheses." when using the logical negation operator. 

However, it appears to be implemented correctly and the program produces the right output.

**Comment by willwolf** [comment]
Should be resolved in beac130a7bdc2ea318e1116226f395649055c5f5.  Please resubmit the code the exposed this issue and verify the issue is resolved.  If you find that it is not resolved, please reopen the issue and let me know :)

**Comment by dharapa** [comment]
Issue has been resolved! (:
