### ISSUE TITLE
Bug Report with operators in single quote

### ISSUE THREAD

**Issue by terryz1** [vianuevm/cppStyle#128]
"Incorrect spacing around /. If this is a negative variable, you must write it as -(myVariable) using parentheses."

**Comment by TheWolfA2** [comment]
This issue was already pointed out in #126 but thank you for making sure it was noticed and handled!

**Comment by willwolf** [comment]
Closing, since this is a duplicate. Also, should be resolved in 87bc0e1b38d50c3ae7f242c35ea702d78e82d71d. If you could resubmit your code and verify that this issue is resolved, it would be greatly appreciated!  If you find that it is not fixed, please reopen issue #126 :)
