### ISSUE TITLE
Issues with nested for loops

### ISSUE THREAD

**Issue by jpdsilva** [vianuevm/cppStyle#130]
When I nested several for loops, it returned "116  Incorrect indentation. Expected: 0, found: 8." I am not sure if this is a bug; I know not everyone indents nested for loops, but I think that the whitespace makes it more legible.

**Comment by willwolfram18** [comment]
This issue should have been fixed in a14009fc9666e4f70036ed380337160e8be3508f. Please feel free to resubmit the code that exposed the issue and let me know if the issue is not resolved! :)
