### ISSUE TITLE
Incorrect spacing around !

### ISSUE THREAD

**Issue by ansnolan** [vianuevm/cppStyle#131]
"113:36  Incorrect spacing around !.  If this is a negative variable, you must write it as -(myVariable) using parentheses."

My code read: 

!(isupper(original[i]))

I believe this is the correct format though I could be wrong

**Comment by TheWolfA2** [comment]
Looks like this issue was addressed in #127 already, but thanks for making sure it was addressed!

**Comment by willwolf** [comment]
Closing since it's already been addressed in #127.  Please feel free to resubmit your code and verify the issue has been resolved!  If you find that it is not fixed, please reopen issue #127 to let me know it still needs fixing :)
